<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWDn3yjh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWDn3yjh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWDn3yjh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWDn3yjh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWDn3yjh\App_KernelDevDebugContainer([
    'container.build_hash' => 'WDn3yjh',
    'container.build_id' => '82f26185',
    'container.build_time' => 1750673282,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWDn3yjh');
