version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: qardapi
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
