<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJrsUwEa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJrsUwEa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJrsUwEa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJrsUwEa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJrsUwEa\App_KernelDevDebugContainer([
    'container.build_hash' => 'JrsUwEa',
    'container.build_id' => '6dccc112',
    'container.build_time' => 1750722592,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJrsUwEa');
