<?php

namespace ContainerJrsUwEa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Grr66HlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Grr66Hl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Grr66Hl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompanyController::list' => ['privates', '.service_locator.a.4KMKr', 'get_ServiceLocator_A_4KMKrService', true],
            'App\\Controller\\QardController::getClients' => ['privates', '.service_locator._7S07uI', 'get_ServiceLocator_7S07uIService', true],
            'App\\Controller\\SynController::syncUser' => ['privates', '.service_locator._7S07uI', 'get_ServiceLocator_7S07uIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CompanyController:list' => ['privates', '.service_locator.a.4KMKr', 'get_ServiceLocator_A_4KMKrService', true],
            'App\\Controller\\QardController:getClients' => ['privates', '.service_locator._7S07uI', 'get_ServiceLocator_7S07uIService', true],
            'App\\Controller\\SynController:syncUser' => ['privates', '.service_locator._7S07uI', 'get_ServiceLocator_7S07uIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CompanyController::list' => '?',
            'App\\Controller\\QardController::getClients' => '?',
            'App\\Controller\\SynController::syncUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CompanyController:list' => '?',
            'App\\Controller\\QardController:getClients' => '?',
            'App\\Controller\\SynController:syncUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
