<?php

namespace ContainerWDn3yjh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCompaniesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportCompaniesCommand' shared autowired service.
     *
     * @return \App\Command\ImportCompaniesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ImportCompaniesCommand.php';

        $container->privates['App\\Command\\ImportCompaniesCommand'] = $instance = new \App\Command\ImportCompaniesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()));

        $instance->setName('app:import-companies');

        return $instance;
    }
}
