<?php

namespace ContainerWDn3yjh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQardApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QardApiService' shared autowired service.
     *
     * @return \App\Service\QardApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'QardApiService.php';

        return $container->privates['App\\Service\\QardApiService'] = new \App\Service\QardApiService(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), $container->getEnv('QARD_API_URL'), $container->getEnv('QARD_API_KEY'));
    }
}
